apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: idm3ru5lj-go 
  janus-idp.io/tekton: idm3ru5lj-go
  backstage.io/kubernetes-id: idm3ru5lj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: idm3ru5lj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  