apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: idm3ru5lj-go
  janus-idp.io/tekton: idm3ru5lj-go
  backstage.io/kubernetes-id: idm3ru5lj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: idm3ru5lj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
