apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: idm3ru5lj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: idm3ru5lj-go 
  name: idm3ru5lj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: idm3ru5lj-go 
